
CREATE TABLE monit_server2(
DIA DATE,
HORA VARCHAR2(5),
SERVERID VARCHAR2(15),
ATIVADIA NUMBER(4),
MEMOLIVRE NUMBER(12),
SWAPUSADO NUMBER(12),
QTDEDCORE NUMBER(3),
CPUSFREE NUMBER(3),
CPULIVRE NUMBER(5,2),
TEMPREDE NUMBER(6,2),
LOADAVER NUMBER(6,2))
ORGANIZATION EXTERNAL
(
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY ext_table
  ACCESS PARAMETERS
  (
    RECORDS DELIMITED BY NEWLINE
    BADFILE ext_table_monit_server2
    LOGFILE ext_table_monit_server2
    DISCARDFILE ext_table_monit_server2
    FIELDS TERMINATED BY ';'
    MISSING FIELD VALUES ARE NULL
    (
    DIA CHAR(6) DATE_FORMAT DATE MASK "RRMMDD",
    HORA,
    SERVERID,
    ATIVADIA,
    MEMOLIVRE,
    SWAPUSADO,
    QTDEDCORE,
    CPUSFREE,
    CPULIVRE,
    TEMPREDE,
    LOADAVER
    )
  )
  LOCATION ('cargaserver.txt')
);
